### ISSUE TITLE
env

### ISSUE THREAD

**Issue by chraibi** [iv-mexx/gitlab-migrator#1]
Could you please explain the difference between

```
FL_GITLAB_ENDPOINT_SRC
```

and

```
FL_GITLAB_TOKEN_SRC
```

in the file `env?`

**Comment by iv-mexx** [comment]
The `ENDPOINT` variables are the URL to your gitlab instance (i.e. to the API), e.g.: `https://gitlab.example.net/api/v3`

The `TOKEN` variables are the private access tokens with which you can access the API, [check this link  to get your private token](https://www.safaribooksonline.com/library/view/gitlab-cookbook/9781783986842/ch06s05.html).

Thanks for bringing this lack of documentation to my attention, I've update the README accordingly in https://github.com/iv-mexx/gitlab-migrator/commit/28ee0f4c9153f9fddc2023d9abfcb5822870d421 and https://github.com/iv-mexx/gitlab-migrator/commit/320eccd295094558acaca9a844be9e3501be77f9 to hopefully clear that up :+1:

**Comment by chraibi** [comment]
Thanks!
