### ISSUE TITLE
User contribution Summary

### ISSUE THREAD

**Issue by chraibi** [iv-mexx/gitlab-migrator#12]
I was just wondering if you already found a way to setup the contribution events for users correctly after merging the projects. 

I understand that the activity of a user starts with the minute the project is migrated to the new server, however I could not find in the [API documentation](https://docs.gitlab.com/ce/api/)
any hints how to modify the activity calendar. 

Any thoughts? Maybe when [mapping the users](https://github.com/iv-mexx/gitlab-migrator/blob/master/fastlane/actions/gitlab_create_project.rb#L16) copy also their [contribution events](https://docs.gitlab.com/ce/api/users.html#get-user-contribution-events) too?

![screen shot 2016-12-15 at 18 25 10](https://cloud.githubusercontent.com/assets/5772973/21234668/e0cda544-c2f3-11e6-9563-d7dfb446de06.png)

**Comment by iv-mexx** [comment]
Hm, it seems there is no way to post contribution events, only to get them so I think this will not be possible.
