### ISSUE TITLE
Difference between namespaces and groups

### ISSUE THREAD

**Issue by chraibi** [iv-mexx/gitlab-migrator#14]
While preparing for the D-day, I found the following problem: 

in `src_server` I have user `joe`
in `dst_server` I have user `joe1` 

These are the same user. I can make sure that is the case with the variable `user_mapping`

Now we want to migrate `joe/foo` to new server. However, `ensure_group()` will tell us that the *group* `joe` does not exist and will create a group `joe`. 

The fact that the group does not exist may be correct, however I think here the [namespace](https://docs.gitlab.com/ce/api/namespaces.html) is of kind "user" and not "group".  

Therefore, the case

```
group = gitlab_dst.namespaces.auto_paginate.select { |g| g.id == dst_owner_id and g.kind == 'user'}.first
```
with 

```
owner_id = original_project.owner.id
dst_owner_id = user_mapping[owner_id]
```

should be inserted in the [else](https://github.com/iv-mexx/gitlab-migrator/blob/master/fastlane/actions/gitlab_create_project.rb#L64)-case.

This worked fine for me, at least.

**Comment by iv-mexx** [comment]
So, `user_mapping` already matches `joe` to `joe1` (based on his name instead of the username?) right?

**Comment by chraibi** [comment]
Correct.

**Comment by iv-mexx** [comment]
Ok, that sounds reasonable. I'll try your PR later

**Comment by chraibi** [comment]
But before, please have a look at this commit too 547fd76
