### ISSUE TITLE
Import Wiki

### ISSUE THREAD

**Issue by chraibi** [iv-mexx/gitlab-migrator#3]
This Code is amazing!  I could migrate my repositories from Gitlab-Server1 to Gitlab-Server2. However, the wiki-pages are not imported. I know these are yet other Git-repos, but would be nice to migrate them too.

**Comment by iv-mexx** [comment]
Yeah that would be great. The initial problem was, that I could not find a way to figure out the repo-url for the wiki repo from the gitlab API. I'll take another look at it, maybe I've overlooked something!

**Comment by chraibi** [comment]
@iv-mexx I did not found something other than [this unanswered question](https://forum.gitlab.com/t/how-to-access-wiki-pages-via-api-gitlab-com-private-repo/930). 

A quick and dirty solution may be appending a `.wiki.git` to the to the project's name and clone the result ...

**Comment by iv-mexx** [comment]
> A quick and dirty solution may be appending a .wiki.git to the to the project's name and clone the result ...

Actually, I think thats good enough. I'll try it!
