### ISSUE TITLE
GitlabCreateProjectAction: Mapping users

### ISSUE THREAD

**Issue by chraibi** [iv-mexx/gitlab-migrator#9]
In this [line](https://github.com/iv-mexx/gitlab-migrator/blob/master/fastlane/actions/gitlab_create_project.rb#L16)

users from `source` who are found in `destination` are mapped. 

But why is this necessary here? User `x` wants to merge its *own* project from `source` to `destination`. So why to we need to map user `y` which has nothing to do with that project?

**Comment by iv-mexx** [comment]
We are using gitlab as a small team with a number of different projects and different groups. 
When we were doing the migration, we already had the users registered in the new gitlab instance, but wanted to automatically create and assigns all the different teams we had.
